#!/bin/bash

APPNAME="$( basename "$0")"
[[ -r "/etc/${APPNAME}.conf" ]] && . "/etc/${APPNAME}.conf"
[[ -r "$HOME/.${APPNAME}.conf" ]] && . "$HOME/.${APPNAME}.conf"

usage() {
  echo "Usage: $0 function" >&2
  echo "Functions: add_project trigger_build rewrite_index remove_project" >&2
  echo "$@" >&2
  echo
  exit 1
}

PROJECTS_DIR="${PROJECTS_DIR:-/var/lib/${APPNAME}}"
WEB_DIR="${WEB_DIR:-$PROJECTS_DIR/web}"
EDITOR="${EDITOR:-vim}"
MAX_JOBS="${MAX_JOBS:-2}"
PROJECTS_HISTORY_LIMIT="${PROJECTS_HISTORY_LIMIT:-20}"
INDEX_HTML="$WEB_DIR/index.html"
PID_PATH_NAME="build.pid"
PID_FILE_NAME="pidfile"
SQLITE_FILE="project.db"
BASHCI_USER="${BASHCI_USER:-$USER}"
BASHCI_TITLE="${BASHCI_TITLE:-Bash-CI Continuous Integration Dashboard}"

PROJECTS_JSON="$WEB_DIR/projects.json"

mkdir -p "${PROJECTS_DIR}" "${WEB_DIR}"

project_basedir() {
  [[ "$1" == "web" ]] && echo "${WEB_DIR}/${PROJECT_NAME}" || echo "${PROJECTS_DIR}/${PROJECT_NAME}"
}

project_workdir() {
  echo "$( project_basedir "$@" )/work"
}

project_buildfile() {
  echo "$( project_basedir )/build.sh"
}

project_pidfile() {
  echo "$( project_basedir )/$PID_PATH_NAME"
}

project_lastbuild() {
  echo "$( project_basedir web)/status.json"
}
project_history() {
  echo "$( project_basedir web )/history.json"
}

project_repodir() {
  echo "$( project_basedir )/repo"
}

projectfile() {
  echo "$( project_basedir)/bashci-project"
}

projectdb() {
  echo "$( project_basedir)/$SQLITE_FILE"
}

project_is_running() {
  local PROJECT_NAME="$1"
  [[ -r "$( project_pidfile )" ]]
}
lock_build() {
  mkdir "$( project_pidfile )"
}

wait_lock() {
  while ! lock_build; do sleep 1; done
}

unlock_build() {
  rm -rf "$( project_pidfile )"
}

projects_builds_running() {
  find "$PROJECTS_DIR" -name "$PID_PATH_NAME" | wc -l
}

wait_for_free_builders() {
  while [[ "$( find "$PROJECTS_DIR" -path "*/$PID_PATH_NAME/${PID_FILE_NAME}" -not -path "$(project_basedir)/*" | wc -l )" -ge "$MAX_JOBS" ]]; do
    sleep 1
  done
}

wait_for_finished() {
  local PROJECT_NAME="$1"
  project_is_running "$PROJECT_NAME" && echo "Project ${PROJECT_NAME} already running, waiting for finished"
  while project_is_running "$PROJECT_NAME"; do
    echo -en "."
    sleep 1
  done
}

git_init_repo() {
  git clone "$1" "$(project_repodir)"
  ( cd "$(project_repodir)" && git submodule init )
}

git_update_repo_command() {
 echo -e "( cd \${REPO_DIR} && git pull && git submodule update; git log -n1 )"
}

update_projects_json() {
  sep=""
  echo -en "[" > "$PROJECTS_JSON"
  find "$PROJECTS_DIR" -name "bashci-project" | sort -n | while read fname; do
    . "$fname"
    echo -en "$sep{\"name\":\"${PROJECT_NAME}\",\"description\":\"$PROJECT_DESCRIPTION\"}" >> "$PROJECTS_JSON"
    echo -en "{\"name\":\"${PROJECT_NAME}\",\"description\":\"$PROJECT_DESCRIPTION\"}" > "$(project_basedir web)/project.json"
    sep=","
  done
  echo -en "]" >> "$PROJECTS_JSON"
}

git_fetch_description() {
  echo -e "\$(cat \"$@/.git/description\")"
}

remove_project() {
  local PROJECT_NAME="$1"
  [ -z "$PROJECT_NAME" ] && usage "remove_project project_name"
  read -ep "About to remove project $PROJECT_NAME. Are you sure? [y/n] " -n1 sure
  [[ "$sure" != "y" ]] && return 1
  rm -rf "$( project_basedir )" "$( project_basedir web )"
  update_projects_json
}

add_project() {
  local PROJECT_NAME="$1"
  repo_type="$2"
  repo_url="$3"
  [ -z "$repo_url" ] && usage "add_project project_name repo_type repo_url (repo type currently supported: git)"
  mkdir -p "$( project_workdir )" "$( project_basedir web )"
  "${repo_type}_init_repo" "$repo_url"
  cat >"$( projectfile )" <<EOF
PROJECT_NAME="$PROJECT_NAME"
PROJECT_DIR="$( project_workdir )"
PROJECT_DESCRIPTION="$(${repo_type}_fetch_description "$( project_repodir )")"
REPO_DIR="$( project_repodir )"
EOF
  sqlite3 "$(projectdb)" <<<"CREATE TABLE builds(id integer primary key not null, started INTEGER, finished INTEGER, exit_code INTEGER, status TEXT);"
  cat >"$( project_buildfile )" <<EOF
#!/bin/bash

. "$( projectfile )"

## $PROJECT_NAME build file. Tweak it and add build options to make it automatically run.
## Available environment variables: PROJECTS_DIR PROJECT_NAME PROJECT_DESCRIPTION REPO_DIR
## You can also parse arguments in "\$@" before starting any build, for instance to set a working branch.


# Update repository function: tweak if needed
bashci_build_00_update_repo() {
  $( "${repo_type}_update_repo_command" )
}

## Name your build functions with bashci_build_nn_name and the CI system will automatically run them in sequence
bashci_build_01_start_build() {
  false
}

## You can also define hooks for build success and failure:

bashci_success_trigger() {
  true
}

bashci_failure_trigger() {
  false
}

EOF
  $EDITOR "$( project_buildfile )"
  update_projects_json
}

split() {
  IFS="|" read -ra SPLITTED <<<"$@"
}

update_project_json() {
  local project_history="$( project_history )"
  local project_lastbuild="$( project_lastbuild )"
  echo -n "[" > "$( project_history )"
  row2json() {
    split "$row"
    row_json="{\"id\": \"${SPLITTED[0]}\", \"started\": \"${SPLITTED[1]}\", \"finished\": \"${SPLITTED[2]}\", \"exit_code\": \"${SPLITTED[3]}\", \"status\": \"${SPLITTED[4]}\"}"
  }
  sqlite3 "$( projectdb )" <<<"select id, started, finished, exit_code, status from builds ORDER BY id DESC LIMIT ${PROJECTS_HISTORY_LIMIT};" | while read row; do
    row2json
    echo -n "$sep${row_json}" >> "${project_history}"
    sep=","
  done
  row="$( sqlite3 "$( projectdb )" <<<"select id, started, finished, exit_code, status from builds ORDER BY id DESC LIMIT 1;" )"
  row2json
  echo -n "$row_json" > "$project_lastbuild"
  echo -n "]" >> "${project_history}"
}

build_project() {
  local PROJECT_NAME="$1"; shift
  [ -r "$( project_buildfile )" ] && . "$( project_buildfile )" # TODO: handle errors
  wait_lock
  wait_for_free_builders
  echo "$BASHPID" > "$(project_pidfile)/${PID_FILE_NAME}"
  build_id="$( sqlite3 "$(projectdb)" <<<"INSERT INTO builds(started, status) VALUES((SELECT datetime('now', 'localtime')), 'building'); select last_insert_rowid();")"
  logfile="$(project_basedir web)/${build_id}.log"
  : > "$logfile"
  log() {
    tee -a "$logfile"
  }
  echo "Build id: $build_id" | log

  build_started_time="$( date -Is )"
  update_project_json
  declare -F| grep bashci_build_ | awk '{ print $3 }' | sort -n | while read fname; do
    echo "============================================================" | log
    echo "$( date -Is ) - Running '${fname#bashci_build_??_}'" | log
    set -o pipefail
    "$fname" 2>&1 | log
    exit_code="$?"
    if [[ "$exit_code" != 0 ]]; then
      unlock_build
      exit $exit_code
    fi
  done
  local exit_code="$?"
  [[ "${exit_code}" == 0 ]] && build_status="success" || build_status="failure"
  sqlite3 "$(projectdb)" <<<"UPDATE builds SET finished=(SELECT datetime('now', 'localtime')), exit_code=$exit_code, status='$build_status' WHERE id = $build_id;"
  echo "$(date -Is) - Build finished: $build_status ($exit_code)" | log
  [[ "$( type -t "bashci_${build_status}_trigger" )" == "function" ]] && bashci_${build_status}_trigger
  update_project_json
  unlock_build
  exit "${exit_code}"
}

trigger_build() {
  local PROJECT_NAME="$1"
  [[ -z "$PROJECT_NAME" ]] && usage "trigger_build project-name"
  build_id="$( date -Is )"
  if ! [[ -d "$( project_workdir )" ]]; then
    echo "ERROR! Project $PROJECT_NAME doesn't exist" >&2
    exit 1
  fi
  logfile="$( project_workdir )/build.log"
  echo "Launched build with id $build_id, logfile: $logfile"
  ( nohup "$0" build_project "$@" > "$logfile" 2>&1 & )2>/dev/null
}

rewrite_index() {
  rm -f "$INDEX_HTML"
  cat > "$INDEX_HTML" <<EOF
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>${BASHCI_TITLE}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <style>
        .build-success:before{
          content:"\2714";
          color: darkgreen;
        }
        .build-failure:before{
          content:"\2718";
          color: darkred;
        }
        .build-building:before{
          content:"\25B6";
          color: darkblue;
        }
        .build-success:before, .build-failure:before, .build-building:before {
          padding-right: 5px;
        }
        li .build-success, li .build-failure, li .build-building {
          padding-left: 1em;
          text-indent: -1em;
        }
    </style>
    <script>
      var showTab = function(name) {
        \$('.tabs-stack').hide();
        \$('#' + name).show();
      };
      var update_project_history_timer = false;
      var update_project_logs_timer = false;
      
      var scrollTo = function(position) {
        \$("html, body").animate({ scrollTop: position }, "slow");
      }
      
      var read_log = function(id, name) {
          jQuery.get( name + "/" + id + ".log", function(log){
              \$('#project-details-build-log').text(log);
          });
          if(following_logs) {
            scrollTo( \$(document).height());
          }
      };
      var tail_log = function(event) {
        \$('.build-item').removeClass('bg-info');
        \$(".build-item[data-build-id='" + event.data.id + "']").addClass('bg-info');
        clearInterval(update_project_logs_timer);
        read_log(event.data.id, event.data.name);
        update_project_logs_timer = setInterval(function() {read_log(event.data.id, event.data.name); }, 1000);
      };
      var showProject = function(name) {
        jQuery.getJSON( name + "/project.json", function(project){
          \$('#project-details-name').html(project.name);
          \$('#project-details-description').html(project.description);
        });
        var update_project_history = function() {
          jQuery.getJSON( name + "/history.json", function(history){
            for(var i = history.length-1; i>=0; i--) {
              var item_status_id = 'build_' + history[i].id + '_status';
              if(\$('#' + item_status_id).length == 0) {
                \$('<li data-build-id="' + history[i].id + '" class="build-item"><a href="#"><span id="' + item_status_id + '"><small>#' + history[i].id + ' ' + history[i].started + '</small></span></a></li>')
                  .prependTo('#project-details-history')
                  .click( {"id": history[i].id, "name": name}, tail_log);
              }
              \$('#' + item_status_id).attr("class", 'build-' + history[i].status);
            }
            \$('.build-item').each(function(index, element){
              var to_delete = true;
              for(var i=0; i<history.length; i++) {
                if(\$(element).data().buildId == history[i].id)
                  to_delete = false;
              }
              if(to_delete)
                \$(element).remove();
            });
          });
        };
        \$('#project-details-history').empty();
        update_project_history();
        \$('#project-details-build-log').empty();
        update_project_history_timer = setInterval(update_project_history, 1000);
        showTab('project-details');
      };
      
      var showDashboard = function() {
        clearInterval(update_project_history_timer);
        clearInterval(update_project_logs_timer);
        showTab('dashboard');
      };
      var loaded_projects = {};
      var add_project = function(project) {
      var tabname=project.name + "_tab";
      var rowname=project.name + "_row";
      \$(".projects").append("<tr id='" + rowname + "'></tr>");
      \$("#" + rowname).html("\
        <td>\
          <a href='#' onclick='showProject(\"" + project.name + "\");'>" + project.name + "</a>\
        </td>\
        <td>" + project.description + "</td>\
        <td id='" + project.name + "_build_started'/>\
        <td><span id='" + project.name +"_dash_status'></span></td>\
        ");
      var show_status = function() {
        jQuery.getJSON( project.name + "/status.json", function(status){
          \$('#' + project.name + '_dash_status').html(status.status).attr("class", "build-" + status.status);
          \$('#' + project.name + '_build_started').html(status.started);
        });
      };
      show_status();
      project['timer'] = window.setInterval(show_status, 1000);
      loaded_projects[project.name] = project;
    }
    var load_projects = function() {
      jQuery.getJSON("projects.json", function(projects){
        for(var i=0; i<projects.length; i++){
          if(loaded_projects[projects[i].name] == undefined)
            add_project(projects[i]);
        }
        for(var project in loaded_projects) {
          var present = false;
          for(var i = 0; i <projects.length; i++) {
            present |= projects[i].name == project;
          }
          if(! present) {
            \$('#' + project + '_row').remove();
            delete loaded_projects[project];
          }
        }
      });
    };
    
    var following_logs = false;
    var follow_logs = function(follow) {
      following_logs = follow;
      if(following_logs) {
        \$('#follow_logs').addClass("active");
      } else {
        \$('#follow_logs').removeClass("active");
      }
    };    
    
    load_projects();
    window.setInterval(load_projects, 1500);
    </script>
  </head>
  <body>
    <div class="page-header" style="margin-top: 20px; margin-left: 10px">
        <h2>${BASHCI_TITLE}</h2>
    </div>
    <div class="container tabs-stack" id="dashboard">
      <h3>Dashboard</h3>
      <table class="table projects table-bordered table-hover table-striped">
        <tr><th>Project</th><th>Description</th><th>Started</th><th>Status</th></tr>
      </table>
    </div>
    <div class="container-fluid tabs-stack" id="project-details" style="display: none">
      <div class="row">
        <h3 class="col-xs-10"><span id="project-details-name"></span><small style="padding-left: 3em;" id="project-details-description"></small></h3>
        <div class="col-xs-2">
          <button id="back-to-dashboard" class="btn btn-primary pull-right" onclick="showDashboard();">Back to dashboard</button>
        </div>
      </div>
      <div class="row">
        <h4 class="col-xs-2">History</h4>
        <h4 class="col-xs-10">Logs</h4>
      </div>
      <div class="row">
        <div class="col-xs-2">
          <ul id="project-details-history" class="list-unstyled"></ul>
          <div style="position: fixed; bottom: 20px;" class="btn-group">
            <button id="scroll_top" class="btn btn-info btn-xs" onclick="follow_logs(false); scrollTo(0);">&#x2191; Up</button>
            <button id="follow_logs" class="btn btn-info btn-xs" onclick="follow_logs(!following_logs);">&#x2193; Follow Logs</button>
          </div>
        </div>
        <div class="col-xs-10"><pre id="project-details-build-log"></pre><a name="logs-bottom" /></div>
      </div>
    </div>
  </body>
</html>
EOF
}

if [[ "$1" == sudo ]]; then
  shift
  if [[ "${BASHCI_USER}" != "$USER" ]]; then
    sudo -Hu "${BASHCI_USER}" "$0" "$@"
    exit $?
  fi
fi

[[ -r "$INDEX_HTML" ]] || rewrite_index

if [[ -n "$1" && "$1" != "--help" && "$( type -t "$1" )" == "function" ]]; then
    update_projects_json
    "$@"
else
    usage
fi
