#!/bin/bash
# codec options: -s hd1080 -vcodec libx264

INPUT_FRAMERATE=1
OUTPUT_FILENAME="timelapse.mp4"
INPUT_MASK="IMG_%04d.JPG"
START_NUMBER=1


print_help() {
    cat >&2 <<EOF
Usage: $0 [options].
Options:
  -o|--output <filename> (default: $OUTPUT_FILENAME)
  -m|--input-mask <input-mask> (default: $INPUT_MASK)
  -s|--start-number <number> (default: $START_NUMBER)
  -f|--output-framerate <framerate> (default: $OUTPUT_FRAMERATE)
  -r|--input-framerate <framerate> (default: $INPUT_FRAMERATE)
  -z|--resize <resolution> (resolution can be either WIDTHxHEIGHT, or 4k/1080p/720p)
  -g|--glob       use glob as mask
  -crf <crf>
  -preset <preset>
EOF
    exit ${1:-1}
}

[ -z "$1" ] && print_help

while [[ -n "$1" ]]; do
    case "$1" in
        -s|--start-number)
            START_NUMBER="$2"; shift
            ;;
        -m|--input-mask)
            INPUT_MASK="$2"; shift
            ;;
        -f|--output-framerate)
            OUTPUT_FRAMERATE_OPTS="-r $2"; shift
            ;;
        -o|--output)
            OUTPUT_FILENAME="$2"; shift
            ;;
        -r|--input-framerate)
            INPUT_FRAMERATE="$2"; shift
            ;;
        -z|--resize)
            if [ "$2" == "4k" ]; then
                res="3840x2160"
            elif [ "$2" == "1080p" ]; then
                res="1920x1080"
            elif [ "$2" == "720p" ]; then
                res="1280x720"
            else
                res="$2"
            fi
            width="$( cut -dx -f1 <<<"$res")"
            height="$( cut -dx -f2 <<<"$res")"
            RESIZE_OPTS="-vf \"scale=$width:$height:force_original_aspect_ratio=decrease,pad=$width:$height:(ow-iw)/2:(oh-ih)/2\""; shift
            ;;
        -crf)
            CRF_OPTS="-crf $2"; shift
            ;;
        -preset)
            PRESET_OPTS="-preset $2"; shift
            ;;
        -g|--glob)
            GLOB_OPTS="-pattern_type glob"
            ;;
        *)
            print_help
            ;;
    esac
    shift
done
set -x
eval "ffmpeg -f image2 -start_number '$START_NUMBER' -r '$INPUT_FRAMERATE' $GLOB_OPTS -i '$INPUT_MASK' $OUTPUT_FRAMERATE_OPTS $RESIZE_OPTS $PRESET_OPTS $CRF_OPTS -vf format=yuv420p '$OUTPUT_FILENAME'"

