#!/bin/bash


INDI_parse_cli() {
  DEV="$DEFAULT_DEVICE"
  while [[ -n "$1" ]]; do
    case "$1" in
      -d|--device)
        DEV="$2"; shift
        ;;
    esac
    shift
  done
}

INDI_set_property_sync() {
  DEV="$1"
  PROPERTY="$2"
  KEY="$3"
  VALUE="$4"
  TIMEOUT="${5:-2}" 
  if [[ -z "$TIMEOUT" ]]; then
    echo "Usage: set_property_sync DEVICE PROPERTY KEY VALUE TIMEOUT"
    exit 1
  fi
  indi_setprop "$DEV.$PROPERTY.$KEY"="$VALUE"
  indi_eval -w -t $TIMEOUT "\"$DEV.$PROPERTY._STATE\"==1"
}

INDI_set_local_upload_dir() {
  INDI_parse_cli "$@"  
  DIR="$1"
  INDI_set_property_sync "$DEV" UPLOAD_MODE UPLOAD_LOCAL On 
  INDI_set_property_sync "$DEV" UPLOAD_SETTINGS UPLOAD_DIR "$DIR"
}

INDI_set_file_prefix() {
  INDI_parse_cli "$@"  
  PREFIX="$1"
  INDI_set_property_sync "$DEV" UPLOAD_SETTINGS UPLOAD_PREFIX "$PREFIX"
}

INDI_expose() {
  INDI_parse_cli "$@"  
  EXPTIME="$1"
  INDI_set_property_sync "$DEV" CCD_EXPOSURE CCD_EXPOSURE_VALUE "$EXPTIME"
}


INDI_session_template() {
  first_device="$( indi_getprop | grep CCD_EXPOSURE | cut -d. -f1 | head -n 1 )"
  device="${first_device:-set default device name here}"
  session_name="$1"
  if [[ -z "$session_name" ]]; then
    echo "Usage: INDI_session_template session_name"
    exit 1
  fi  
  mkdir -p "$session_name"
  cp "$0" "$session_name/"
  cat > "$session_name/start_sequence" <<EOF
#!/bin/bash
export DEFAULT_DEVICE="$device"
export SESSION_NAME="$session_name"

# Read a local copy of the indi_helper script
. indi_helper

update_file_prefix() {
  image_type="\$1"
  exposure="\$2"
  INDI_set_file_prefix "\${SESSION_NAME}_\${image_type}_\${exposure}secs_XXX"
}

INDI_set_local_upload_dir "\$PWD"

# Loop for each image type
for img_type in Luminance Red Green Blue Dark; do
  # loop for each exposure
  for exp in 5 15 60; do
    # Set local directory for image saving
    update_file_prefix "\$img_type" "\$exp"
    for i in {1..20}; do
      # Start exposure
      INDI_expose "\$exp"
    done
  done
done
EOF
chmod a+x "$session_name/start_sequence"
}

if [[ "$( basename "$0" )" == "indi_helper" ]] && [[ "$1" == "create-script" ]]; then
    shift
    INDI_session_template "$@"
fi
