#!/bin/bash
function usage() {
    echo "Usage: `basename $0` filename [interpreter path]"
    exit 0
}

SCRIPT_FILE="$1"; shift

if test "x$SCRIPT_FILE" == "x"; then
    usage
fi


INTERPRETER="$@"
if [ -z "$INTERPRETER" ]; then
    INTERPRETER="/usr/bin/env bash"
fi

if [ -r $SCRIPT_FILE ]; then
    echo "File $SCRIPT_FILE already present, opening"
    vim $SCRIPT_FILE
    exit 0
fi

cat >$SCRIPT_FILE <<EOF
#!$INTERPRETER

EOF

chmod +x $SCRIPT_FILE
vim $SCRIPT_FILE +2

