#!/bin/bash
function usage() {
    echo "Usage: `basename $0` filename [interpreter path]"
    exit 0
}

SCRIPT_FILE="$1"; shift

if test "x$SCRIPT_FILE" == "x"; then
    usage
fi

#INTERPRETER="$( which bash 2>/dev/null)"
INTERPRETER="/bin/bash"

if test "x$1" != "x"; then
    if ! [ -r $1 ]; then
        echo "Error! Interpreter \"$1\" not found"
        usage
    else
        INTERPRETER="$@"
    fi
fi

if [ -r $SCRIPT_FILE ]; then
    echo "File $SCRIPT_FILE already present, opening"
    vim $SCRIPT_FILE
    exit 0
fi

cat >$SCRIPT_FILE <<EOF
#!$INTERPRETER

EOF

chmod +x $SCRIPT_FILE
vim $SCRIPT_FILE +2

