#!/usr/bin/env python3
import getpass
import argparse

parser = argparse.ArgumentParser('Print single chars from password')
parser.add_argument('digits', action="extend", nargs="+", type=int)

args = parser.parse_args()

passwd = getpass.getpass()
for digit in args.digits:
    print(f'{digit}: {passwd[digit-1]}')
