function(add_gtest)
  set(oneValueArgs NAME TYPE)
  set(multiValueArgs SOURCES TARGET_LINK_LIBRARIES)
  cmake_parse_arguments(add_gtest "${options}"  "${oneValueArgs}" "${multiValueArgs}" "${ARGN}")
  #message("adding test: name=${add_gtest_NAME}, type=${add_gtest_TYPE}, sources: ${add_gtest_SOURCES}, link: ${add_gtest_TARGET_LINK_LIBRARIES}")
  set(test_name test_${add_gtest_TYPE}_${add_gtest_NAME})
  add_executable(${test_name} ${add_gtest_SOURCES})
  target_link_libraries(${test_name} ${add_gtest_TARGET_LINK_LIBRARIES} gtest_main pthread)
  add_dependencies(compile_${add_gtest_TYPE}_tests ${test_name})
  add_test(NAME ${add_gtest_NAME} COMMAND ${test_name})
  GTEST_ADD_TESTS(${test_name} "" ${add_gtest_SOURCES})
endfunction(add_gtest)
